name: Test

on:
  push:
    branches: ["master", "dev", "autotest"]
  pull_request:
    branches: ["master", "dev"]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.9.3]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SOLPSTESTSAMPLES_SSH_KEY}}
            ${{ secrets.DVC_SSH_KEY }}
      - name: Configure ssh
        run: |
          echo "${{ secrets.DVC_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.DVC_SSH_CONFIG }}" >> ~/.ssh/config
      - uses: iterative/setup-dvc@v1
      - name: DVC Pull
        run: |
          dvc pull
      - uses: julia-actions/cache@v1
      - name: Install dependencies
        run: |
          julia --project=. -e 'using Pkg; Pkg.rm(["IMASDD"]); Pkg.add(url="git@github.com:ProjectTorreyPines/IMASDD.jl.git", rev="master")'
      - uses: julia-actions/julia-runtest@v1
      # Not set up yet
      # - uses: julia-actions/julia-processcoverage@v1
      # - uses: codecov/codecov-action@v4
      #   with:
      #     files: lcov.info